#!/bin/bash
cd /home/mp-490/Desktop/IT490BPoc
sudo git pull

#gets most recent PR branch
CURRBRANCH=$(git branch -a | grep remotes/origin/PR* | sort -rn | head -n 1 | cut -d/ -f3)

git checkout $CURRBRANCH

sudo git pull
